<a href="https://colab.research.google.com/github/skandanyal/Udacity_Foundations_of_Generative_AI/blob/main/Udacity_Pytorch_Training_Loop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Training loop

## Create a Number Sum Dataset

In [ ]:
import torch
from torch.utils.data import Dataset

In [ ]:
class NumberSumDataset(Dataset):
    def __init__(self, data_range=(1,10)):
        self.numbers = list(range(data_range[0], data_range[1]))

    def __getitem__(self, index):
        number1 = float(self.numbers[index // len(self.numbers)])
        number2 = float(self.numbers[index % len(self.numbers)])
        return torch.tensor([number1, number2]), torch.tensor([number1 + number2])

    def __len__(self):
        return len(self.numbers) ** 2

In [ ]:
dataset = NumberSumDataset(data_range=(1,100))

for i in range(50, 60):
    print(dataset[i])

(tensor([ 1., 51.]), tensor(52.))
(tensor([ 1., 52.]), tensor(53.))
(tensor([ 1., 53.]), tensor(54.))
(tensor([ 1., 54.]), tensor(55.))
(tensor([ 1., 55.]), tensor(56.))
(tensor([ 1., 56.]), tensor(57.))
(tensor([ 1., 57.]), tensor(58.))
(tensor([ 1., 58.]), tensor(59.))
(tensor([ 1., 59.]), tensor(60.))
(tensor([ 1., 60.]), tensor(61.))


Creating a Multilayer Perceptron with 128 hidden layers

In [ ]:
class MLP(torch.nn.Module):
    def __init__(self, input_size):
        super(MLP, self).__init__()
        self.hidden_layer = torch.nn.Linear(input_size, 128)
        self.output_layer = torch.nn.Linear(128, 1)
        self.activation = torch.nn.ReLU() # Activation function

    def forward(self, x):
        x = self.activation(self.hidden_layer(x))
        return self.output_layer(x)

Instantiate Components Needed for Training

In [ ]:
from torch.utils.data import DataLoader

dataset = NumberSumDataset(data_range=(0,100))
dataloader = DataLoader(dataset, batch_size=100, shuffle=True)
model = MLP(input_size=2)
loss_function = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

Create a Training Loop

In [ ]:
# Train model for 10 epochs
for epoch in range(30):
    epoch_loss = 0.0
    for number_pairs, sums in dataloader: # iterate over batches
        predictions = model(number_pairs) # compute the model output
        loss = loss_function(predictions, sums) # compute the loss
        loss.backward() # perform backpropagation
        optimizer.step() # update the parameters
        optimizer.zero_grad() # zero the gradients

        epoch_loss += loss.item()

    # Peint the loss for this epoch
    print(f"Epoch {epoch}: Sum of Batch losses = {epoch_loss:.5f}.")

Epoch 0: Sum of Batch losses = 46174.48047.
Epoch 1: Sum of Batch losses = 16.14861.
Epoch 2: Sum of Batch losses = 6.21353.
Epoch 3: Sum of Batch losses = 3.84963.
Epoch 4: Sum of Batch losses = 2.59699.
Epoch 5: Sum of Batch losses = 1.85646.
Epoch 6: Sum of Batch losses = 1.42251.
Epoch 7: Sum of Batch losses = 1.12149.
Epoch 8: Sum of Batch losses = 0.91622.
Epoch 9: Sum of Batch losses = 0.73858.
Epoch 10: Sum of Batch losses = 0.63497.
Epoch 11: Sum of Batch losses = 0.53962.
Epoch 12: Sum of Batch losses = 0.47068.
Epoch 13: Sum of Batch losses = 0.44677.
Epoch 14: Sum of Batch losses = 0.39079.
Epoch 15: Sum of Batch losses = 0.36014.
Epoch 16: Sum of Batch losses = 0.33057.
Epoch 17: Sum of Batch losses = 0.31856.
Epoch 18: Sum of Batch losses = 0.28578.
Epoch 19: Sum of Batch losses = 0.26262.
Epoch 20: Sum of Batch losses = 0.24047.
Epoch 21: Sum of Batch losses = 0.20654.
Epoch 22: Sum of Batch losses = 0.20847.
Epoch 23: Sum of Batch losses = 0.18944.
Epoch 24: Sum of Batc

Damn, that is some huge loss values that we see...

Try the model out

In [ ]:
# test the model on 10 + 15
# test_input = torch.tensor([10.0, 15.0]).unsqueeze(0)
# model(test_input().item())

test_input = torch.tensor([10.0, 15.0]).unsqueeze(0)  # Ensure correct shape
print("Prediction for (10,15):", model(test_input).item())

Prediction for (10,15): 24.95871925354004
